### ISSUE TITLE
Segfault in PHP 7.2

### ISSUE THREAD

**Issue by goodexperience** [aerospike-community/aerospike-client-php#11]
Hi,
I am getting 
php[10629]: segfault at 8 ip 00007f471a5a13b2 sp 00007fffb3d09370 error 4 in aerospike.so[7f471a502000+1b1000] after construct in php 7.2.

Simple test case
$config = array("hosts" => array(array("addr" => '127.0.0.1', "port" => '3000')));
$db = new Aerospike($config, false);

Best regards

**Comment by aerospikerobertmarks** [comment]
Hi @goodexperience ,

Thanks for letting us know about this. I have a few more questions which may help me track down the issue:

Which version of the PHP Client are you using?
Which OS are you using?

Do you have a core file which you could provide a larger stack trace from?

Thanks again for letting us know about the issue.

**Comment by short-bench** [comment]
Hi @aerospikerobertmarks I just got the same issue as @goodexperience 

PHP Version
```
PHP 7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b (cli) (built: Mar  6 2018 13:14:13) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

Aerospike PHP Client version is `7.1.1`
OS: `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux`

And this is the output of the core dump file:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php-fpm: pool development-zed-7.2                                 '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  aerospike_close (as=0x0, err=0x7ffcc111ee00) at src/main/aerospike/aerospike.c:177
177	src/main/aerospike/aerospike.c: No such file or directory.
```

Let me know if you need any more information.

**Comment by aerospikerobertmarks** [comment]
Hi @ivan-atanasov , thanks for reporting that, I'll look into how the client could get into that state.

Do you have a section of code which can cause this crash to happen consistently?

**Comment by aerospikerobertmarks** [comment]
Also if you could post a few more levels deep into that stack trace from the core file it would be useful.

**Comment by aerospikerobertmarks** [comment]
Hi @ivan-atanasov We've made an update to the client which we believe should prevent that issue from happening again. It is in version 7.1.2 . Please re-open this issue if the problem persists.
