### ISSUE TITLE
PHP Client serializes all data, even supported formats

### ISSUE THREAD

**Issue by cpats007** [aerospike-community/aerospike-client-php#17]
Hi

I have an issue trying to write data to the aerospike server, in that it seems to be serializing all data, regardless of whether it's a supported format or not. As an example (I've omitted some code, like key gen etc):

```php
$aerospikeOptions = [
    Aerospike::OPT_POLICY_KEY    => Aerospike::POLICY_KEY_SEND,
    Aerospike::OPT_POLICY_EXISTS => Aerospike::POLICY_EXISTS_CREATE_OR_REPLACE
];

$testData['this'] = 'that';

// Write the Main Data to Aerospike:
$check = $this->writeDataToAeroSpike($key, 'namespace', 'set_name', $testData, $aerospikeOptions);
```

If I look at the data written into Aerospike, I can see the following:

```
aql> select * from namespace.set_name
+----+----------------------------------+
| PK | this                             |
+----+----------------------------------+
| 1  | 73 3A 34 3A 22 74 68 61 74 22 3B |
+----+----------------------------------+
1 row in set (0.067 secs)
```

If a enter the data manually via AQL like this:

`aql> insert into adspruce.rtb_floors (PK, 'this') VALUES ('1', 'that')`

I then get:

```
aql> select * from namespace.set_name
+----------------------------------+----+
| this                             | PK |
+----------------------------------+----+
| "that"                           |    |
| 73 3A 34 3A 22 74 68 61 74 22 3B | 1  |
+----------------------------------+----+
2 rows in set (0.067 secs)
```

as you can see it works fine doing it via aql, but via the PHP client, it's simply not doing it.

Any idea why, and any settings that may be causing it? I've tried casting the data to a string, and I've also tried doing it with integers, strings and lists and everything is the same, all being serialized.

PHP version: 7.1.8
Aerospike version: 7.0.3
Server version: 3.10.0

Thanks

**Comment by aerospikerobertmarks** [comment]
Hi @cpats007 

I haven't been able to replicate that issue, but I'll keep trying.
 Are you getting that same behavior if you do something like:

```php
$client->put($client->initKey("test", "demo", 5), ["this" => "that"], 0, $aerospikeOptions);
```

Is this a new issue in 7.0.3, or has it been that way in previous versions as well?

**Comment by cpats007** [comment]
Update:

If I add the following to the options...

`Aerospike::OPT_SERIALIZER => Aerospike::SERIALIZER_NONE`

I then get this as an error:

`Failed to write Data to Aerospike: [-2]: Unable to convert value to as type`

so seems to me for some reason it's having an issue in simply writing basic values to the server?

**Comment by cpats007** [comment]
Okay so following the chain, it turns out it was a function further down which was checking values - despite that it was not changing anything it must have been altering the reference - thanks for the support in checking for me - this can be closed now 👍

**Comment by aerospikerobertmarks** [comment]
No problem @cpats007 , thanks for your interest.
