### ISSUE TITLE
unable install via composer install

### ISSUE THREAD

**Issue by saurovh** [aerospike-community/aerospike-client-php#20]
![screen shot 2018-06-04 at 4 50 55 pm](https://user-images.githubusercontent.com/3105367/40913948-2a325714-6818-11e8-981d-a222c6224c6e.png)

**Comment by aerospikerobertmarks** [comment]
HI @saurovh ,

If you need that version specifically, it can be found in https://github.com/aerospike/aerospike-client-php5 .
