### ISSUE TITLE
Build error (manually or via composer)

### ISSUE THREAD

**Issue by alexchuin** [aerospike-community/aerospike-client-php#21]
Hi,

When I try to build the extension, I always have this error : 

info: extracting files from 'aerospike-client-c-devel-4.1.8.debian9.x86_64.deb'
dpkg-deb: error: 'aerospike-client-c-devel-4.1.8.debian9.x86_64.deb' is not a debian format archive

I'm running on 
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

Thanks for your help !
Alex

**Comment by aerospikerobertmarks** [comment]
Thanks for reporting this, we're looking into the issue.

**Comment by aerospikerobertmarks** [comment]
Hi @alexchuin , This should be fixed with the 7.2.0 release. Thanks again for bringing up the issue.
