### ISSUE TITLE
API documentation BADLY broken

### ISSUE THREAD

**Issue by ctrix** [aerospike-community/aerospike-client-php#23]
The API Reference documentation for PHP at this page:
https://www.aerospike.com/docs/

Brings to a broken page:
https://www.aerospike.com/apidocs/php/

That seems to contain a broken RTF document.

Please fix. That's the only place where documentation is available in a consistent way.

**Comment by aerospikerobertmarks** [comment]
Thanks for reporting this. We're working to resolve the issue.

**Comment by rbotzer** [comment]
In the meanwhile you can [generate your own documentation](https://github.com/aerospike/aerospike-client-php/tree/master/doc#generating-documentation-with-phpdocumentor) using phpDocumentor.

**Comment by aerospikerobertmarks** [comment]
Hi @ctrix ,

The issue should now be resolved. Thanks for reporting this.
