### ISSUE TITLE
Duplicated constant in aerospike doc file

### ISSUE THREAD

**Issue by MortalFlesh** [aerospike-community/aerospike-client-php#27]
Hello,

As I mentioned in https://github.com/aerospike/aerospike-client-php/pull/26 I've found some fatal errors in docs, which I guess is used to autocomplete in the IDE.

I've added missing semicolons, but there is still one fatal error - duplicated constant `OPT_SOCKET_TIMEOUT` - I would gladly fix it but I don't know, which one is correct.. 

There is one on
https://github.com/aerospike/aerospike-client-php/blob/master/doc/phpdoc/aerospike.php#L3365
and the second one on 
https://github.com/aerospike/aerospike-client-php/blob/master/doc/phpdoc/aerospike.php#L3600

**Comment by aerospikerobertmarks** [comment]
Hi @MortalFlesh , excellent find.

The definition on: https://github.com/aerospike/aerospike-client-php/blob/master/doc/phpdoc/aerospike.php#L3600 

is the correct version.

**Comment by aerospikerobertmarks** [comment]
Resolved in 7.3.0. Thanks again for the fix.
