### ISSUE TITLE
Install Issue on Ubuntu 18.04 aarch64

### ISSUE THREAD

**Issue by dercoder** [aerospike-community/aerospike-client-php#29]
I tried to install the aerospike php client:

```
/usr/bin/ld: skipping incompatible /tmp/vendor/aerospike/aerospike-client-php/src/../aerospike-client-c/lib/libaerospike.a when searching for -laerospike
/usr/bin/ld: cannot find -laerospike
collect2: error: ld returned 1 exit status
Makefile:280: recipe for target 'aerospike.la' failed
make: *** [aerospike.la] Error 1
The build has failed...exiting
Script cd src && ./build.sh handling the post-install-cmd event returned with error code 3
```

on

`4.15.0-1028-aws #29+nutmeg8-Ubuntu SMP Tue Nov 20 02:59:41 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux`

i tried the same installation on 

`4.15.0-1021-aws #21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

and it worked fine.

**Comment by aerospikerobertmarks** [comment]
Hi,

Thanks for reporting this.
Our client does not currently work on non x86-64 architectures.

**Comment by agrubb86** [comment]
I have a working PHP client on aarch64. I had to download the aerospike-client-c and modify a couple of Makefiles to replace -march=nocona with -march=native, then build it and make install. After that, I was able to install the PHP client using the instructions at [the install page](https://www.aerospike.com/docs/client/php/install/index.html). Just thought I'd drop this here in case people come across this page and don't think it's possible.

**Comment by agrubb86** [comment]
> 
> 
> I have a working PHP client on aarch64. I had to download the aerospike-client-c and modify a couple of Makefiles to replace -march=nocona with -march=native, then build it and make install. After that, I was able to install the PHP client using the instructions at [the install page](https://www.aerospike.com/docs/client/php/install/index.html). Just thought I'd drop this here in case people come across this page and don't think it's possible.

Update: discovered this is not stable, do not do this in production.
