### ISSUE TITLE
Aerospike status codes const values commented out in Aerospike Class

### ISSUE THREAD

**Issue by cpats007** [aerospike-community/aerospike-client-php#6]
Is there any reason why the status code const values were commented out in the Aerospike Class? Makes it harder in the IDE to show what options are available, what error messages etc are also available:

```php
/*
    // Aerospike Status Codes:
    //
    // Each Aerospike API method invocation returns a status code
    //  depending upon the success or failure condition of the call.
    //
    // The error status codes map to the C client
    //  src/include/aerospike/as_status.h

    // Client status codes:
    //
    const ERR_PARAM              ; // Invalid client parameter
    const ERR_CLIENT             ; // Generic client error

    // Server status codes:
    //
    const OK                     ; // Success status
    const ERR_SERVER             ; // Generic server error
    const ERR_SERVER_FULL        ; // Node running out of memory/storage
    const ERR_DEVICE_OVERLOAD    ; // Node storage lagging write load
    const ERR_TIMEOUT            ; // Client or server side timeout error
    const ERR_CLUSTER            ; // Generic cluster discovery and connection error
    const ERR_CLUSTER_CHANGE     ; // Cluster state changed during the request
    const ERR_REQUEST_INVALID    ; // Invalid request protocol or protocol field
    const ERR_UNSUPPORTED_FEATURE;
    const ERR_NO_XDR             ; // XDR not available for the cluster
    // Record specific:
    const ERR_NAMESPACE_NOT_FOUND;
```

Any chance these can be reinstated please?

**Comment by rbotzer** [comment]
Hey Craig, the constants in your code sample aren't commented out. Those are comments...
The file in the old PHP5 repo and here are the same.  Can you clarify please?

**Comment by kportertx** [comment]
@rbotzer See the first line of the code block.

**Comment by rbotzer** [comment]
I do see that, but that code is not from this repo? @cpats007  can you point to the URL for this file?

**Comment by cpats007** [comment]
the code is from https://github.com/aerospike/aerospike-client-php/blob/master/doc/phpdoc/aerospike.php

when you click reference the Aerospike in the IDE (PhpStorm in this case) it links to that file, which has the constant values commented out, hence it not showing.

**Comment by cpats007** [comment]
As an example, multiple declarations and then commented out code:

![image](https://user-images.githubusercontent.com/5278964/32574324-c778260a-c4c8-11e7-9627-baec39c6ddde.png)

![image](https://user-images.githubusercontent.com/5278964/32574344-d97d8674-c4c8-11e7-86eb-2a1bc5b4ebbf.png)

**Comment by aerospikerobertmarks** [comment]
Hi @cpats007 ,
Thanks for pointing that out, it will be fixed in the next version of the client.

**Comment by aerospikerobertmarks** [comment]
Those codes have been uncommented in the 7.0.3 release. @cpats007  Thanks again for reporting the problem, and please let us know if the issue has not been resolved.

**Comment by cpats007** [comment]
Looks good, thanks @aerospikerobertmarks 👍

**Comment by cpats007** [comment]
Sorry @aerospikerobertmarks - just looking at this again - the comments have been removed and the constants are there but have no values - so something like `const ERR_PARAM; // Invalid client parameter` is actually reporting as an error, as it should be something like `const ERR_PARAM = 1; // Invalid client parameter` shouldn't it?

**Comment by aerospikerobertmarks** [comment]
Hi @cpats007 , no problem with reopening this if it's still an issue.

On that issue: we intended for those values to be opaque to the end user. It shouldn't matter that `ERR_PARAM is -2`, or if it happened to be `"err_param"` instead. Most of that is to encourage users not to use the actual values of the constants, but the constants themselves.

It is unlikely that the values of the constants will change in future versions, but not entirely impossible. 

We'll look into the issue a little more and see if we can find a good way to document the constants' values without encouraging them to be used directly.

**Comment by cpats007** [comment]
Absolutely, I agree that they should be using the constants if they want to ensure compatibility etc, but the point I'm making is that code currently declares empty constants, which I'm not sure is allowed in PHP - that's what I mean. The values can be anything, but there are *no* values currently.

**Comment by rbotzer** [comment]
Craig, you're talking about a stub written in PHP, intended for IDEs and PHPDoc generation. It is not executable code, but it'll be parseable.  The code is actually in the C extension, which definitely defines constants, and those are enumerated.

In your PHP code you need to check for Aerospike::ERR_PARAM or use Aerospike::LOG_LEVEL_INFO. You do not need to care about what their numeric value is, that's the purpose of using constants. Definitely don't try to check for -2 or 1 or whatnot, because those can and do change.  Use the constants. When we push out the fully fleshed PHPDoc stub we won't be urgently trying to keep in sync with the C client's numeric values for those constants - there's no point to it.

**Comment by cpats007** [comment]
Just to clarify @rbotzer I am using the constants, NOT the values (or checking against any values) - I'm simply pointing out that as you stated (this is for IDE's and PHPDoc creation etc only) and the IDE is showing that the file has errors...

![image](https://user-images.githubusercontent.com/5278964/33062631-d2a58bde-ce97-11e7-9d14-764583966e34.png)

Hope that helps - I know this doesn't break anything - call it aesthetics 😄

**Comment by rbotzer** [comment]
The commented out section in the bottom is my TODO of things that remain to be documented. They'll be filled out as above, according to the gloriously ancient JavaDoc clone, PHPDoc.

**Comment by cpats007** [comment]
No worries :)
