### ISSUE TITLE
Class Aerospike being declared as "final" but can't see where?

### ISSUE THREAD

**Issue by cpats007** [aerospike-community/aerospike-client-php#8]
Hi.

I'm trying to build unit tests for applications using the Aerospike class, and when mocking the class am getting the following issues again:

`PHPUnit_Framework_Exception: Class "Aerospike" is declared "final" and cannot be mocked`

I've had this before, but I could clearly see where it was being declared as final, but in this instance, I can't see that it is being declared as final? Any issues anyone can see with this? Below is osme example code for reproduction:

```php
$this->mockAerospike = $this->getMockBuilder(Aerospike::class)
            ->disableOriginalConstructor()
            ->setMethods(['isConnected', 'get', 'put', 'increment', 'exists'])
            ->getMock();
```

Many thanks

**Comment by aerospikerobertmarks** [comment]
I haven't seen that issue before, but somebody else may have.

Are you able to create a subclass of Aerospike outside of PHPUnit ? Something like:

```php
$config = ['hosts'=>[['addr'=>'127.0.0.1', 'port'=>3000]]];

class AerospikeTwo extends Aerospike
{
    public function print_aerospike($string)
    {
        echo 'Aerospike is my name';
    }
}

$a_two = new AerospikeTwo($config);
$k = $a_two->initKey("test", "demo", "1");

$a_two->put($k, ["Aero" => "spike"]);
$a_two->get($k, $response);

var_dump($response)
```

**Comment by cpats007** [comment]
Yep, I can extend the class fine in application code, just not in unit tests which is why I'm wondering where the definition is coming from. I've removed everything and reinstalled the Aerospike class and still seems to be the same so I'm not sure why is it being declared or picked up from somewhere

**Comment by rbotzer** [comment]
The code shows that it's extensible, so it's not final.

**Comment by cpats007** [comment]
Yep, I agree with that @rbotzer - just wondered whether you'd have experience in understanding why it may happen when creating mock objects? If not I'll look into it further.

Thanks

**Comment by aerospikerobertmarks** [comment]
I'm not sure why that would be. It could be that PHPUnit's mocking runs into issues with classes defined in C extensions rather than through PHP userland code.

**Comment by cpats007** [comment]
Quite possibly - I know it used to work, and with the upgrade to the v7 mod it no longer does 🤔

**Comment by cpats007** [comment]
Got it - turned out there was an old version of the C extension installed which was working fine with the new lib files - removed, reinstalled C extension, updated - all good - sorry guys 👍
